Initial version
gadget-tester/user-repo pull request #1
Opened 2015-01-13 12:59 UTC by elbrujohalcon

2015-01-13 12:59 UTC, gadgetci commented on src/gadget_user.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: "%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL".

2015-01-13 16:35 UTC, gadgetci commented on src/gadget_user_warning.erl
> +warning(Something) -> unused.
Warning: variable 'Something' is unused

2015-01-13 16:35 UTC, gadgetci commented on src/gadget_user_warning.erl
> +warning(Something) -> unused.
Warning: missing specification for function warning/1

2015-01-14 15:20 UTC, gadgetci commented on src/gadget_user.erl
> +%% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL
Line 26 is too long: %% LOOK MA, A VERY VERY VERY LONG LINE WITH ALL CAPS AND REALLY NO MEANING AT ALL.

2015-01-14 18:18 UTC, gadgetci commented on src/gadget_user_warning.erl
> +warning(_Something) -> unused.
Warning: missing specification for function warning/1

2015-01-14 20:00 UTC, gadgetci commented on src/gadget_user_warning.erl
> +warning(Something, Else) -> unused.
Warning: variable 'Something' is unused

2015-01-14 20:00 UTC, gadgetci commented on src/gadget_user_warning.erl
> +warning(Something, Else) -> unused.
Warning: variable 'Else' is unused

2015-01-14 20:00 UTC, gadgetci commented on src/gadget_user_warning.erl
> +warning(Something, Else) -> unused.
Warning: missing specification for function warning/2

2017-06-28 18:11 UTC, elvisci requested changes
- Dependency 'sync' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'lager' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'eper' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'katana' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'
- Dependency 'worker_pool' is not using appropriate protocol, please change this to something like '(https://.*|[0-9]+([.][0-9]+)*)'

2018-07-19 18:14 UTC, elbrujohalcon commented
This PR is useless now 😢

2018-07-19 18:14 UTC, closed without merging